apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager-sa
  name: controller-manager
  namespace: dcp-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: configmapsyncer-cr
  name: configmapsyncer-cr
rules:
  - apiGroups: ["syncer.custom"]
    resources: ["configmapsyncers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["syncer.custom"]
    resources: ["configmapsyncers/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "update", "delete", "patch", "get", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "update", "delete", "patch", "get", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create", "update", "delete", "patch", "get", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create","patch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: configmapsyncer-crb
  name: configmapsyncer-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: configmapsyncer-cr
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: dcp-test

