# permissions for end users to edit configmapsyncers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: configmapsyncer-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dynamicconfigmappropagator
    app.kubernetes.io/part-of: dynamicconfigmappropagator
    app.kubernetes.io/managed-by: kustomize
  name: configmapsyncer-editor-role
rules:
- apiGroups:
  - syncer.custom
  resources:
  - configmapsyncers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - syncer.custom
  resources:
  - configmapsyncers/status
  verbs:
  - get
